apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: production
 name: tekkadan-prod
 labels: 
   app: landing-page-tekkadan
spec:
 replicas: 3
 selector: 
   matchLabels:
     app: tekkadan
 template:
   metadata:
     labels:
       app: tekkadan
   spec: 
     containers:
     - name: tekkadan
       image: maximalyono/tekkadan-ci:BUILD_NUMBER
       ports:
       - containerPort: 80

